#!/bin/bash

tags=(
    in-ablat-gscond-log-q-qc-rnn-e2c20e
    in-ablat-gscond-log-q-qc-dense-e2c20e
    in-ablat-log-q-qc-rnn-e2c20e
    in-ablat-log-q-qc-dense-e2c20e
    in-ablat-log-q-qc-exclusive-rnn-e2c20e
    in-ablat-log-q-qc-exclusive-dense-e2c20e
    in-ablat-gscond-rnn-e2c20e
    in-ablat-gscond-dense-e2c20e
    in-ablat-base-rnn-e2c20e
    in-ablat-base-dense-e2c20e
)

group="$(openssl rand -hex 3)"
image=9a68fb66d235223056812cc302fe0c2fe2717a53

for tag in ${tags[@]}
do

    url=gs://vcm-ml-experiments/microphysics-emulation/2022-02-24/${tag}/model.tf
    run_tag=${tag}-10d-${group}

    argo submit ../argo/prog-run-and-eval.yaml \
        -p tag=$run_tag \
        -p image_tag=$image \
        -p config=$(base64 --wrap 0 ../configs/default.yaml) \
        -p tf_model=$url

done

