#!/bin/bash


exps=(
    "2022-03-01/in-ablat-pressure-dense-f64313"
    "2022-03-01/in-ablat-gscond-log-q-qc-pressure-dense-f64313"
    "2022-02-27/in-ablat-gscond-log-q-qc-dense-0a08eb"
    "2022-02-25/in-ablat-log-q-qc-exclusive-dense-4201be"
    "2022-02-25/in-ablat-gscond-dense-4201be"
    "2022-02-25/in-ablat-log-q-qc-dense-4201be"
    "2022-02-25/in-ablat-base-dense-4201be"
)


image=latest

for exp in ${exps[@]}
do
    tag=$(echo $exp | sed --expression='s/^.\{11\}//')-30d-v1
    # url=gs://vcm-ml-experiments/microphysics-emulation/$exp/model.tf

    # yq  --arg url "$url" '.zhao_carr_emulation.model.path |= $url' ../configs/default.yaml > config.yaml
    # trap 'rm config.yaml' EXIT

    # argo submit ../argo/prog-run-and-eval.yaml \
    #     --name "$tag" \
    #     -p image_tag="$image" \
    #     -p tag=$tag \
    #     -p config=$(base64 --wrap 0 config.yaml) | grep -v 'config:' | tee -a submitted-jobs.txt
    argo get $tag
done