#!/bin/bash

tags=(
    tscale-ablat-all-rnn-302ee0
    tscale-ablat-all-dense-302ee0
    tscale-ablat-qc-q-rnn-302ee0
    tscale-ablat-qc-q-dense-302ee0
    tscale-ablat-qc-rnn-302ee0
    tscale-ablat-qc-dense-302ee0
    tscale-ablat-no-scaling-rnn-302ee0
    tscale-ablat-no-scaling-dense-302ee0
)

group="$(openssl rand -hex 3)"
image=9a68fb66d235223056812cc302fe0c2fe2717a53

for tag in ${tags[@]}
do

    url=gs://vcm-ml-experiments/microphysics-emulation/2022-02-24/${tag}/model.tf
    run_tag=${tag}-10d-${group}

    argo submit ../argo/prog-run-and-eval.yaml \
        -p tag=$run_tag \
        -p image_tag=$image \
        -p config=$(base64 --wrap 0 ../configs/default.yaml) \
        -p tf_model=$url

done

