#!/bin/bash

exps=(
    dqc-precpd-limiter-rnn-87e803
    dqc-precpd-limiter-rnn-control-87e803
    dqc-precpd-limiter-rnn-limited-qc-87e803
)


image=ad5b1e91472f34cad97cd8b5aead1dbbfdb09c42

for exp in ${exps[@]}
do
    tag=$exp-30d-v1
    url=gs://vcm-ml-experiments/microphysics-emulation/2022-03-29/${exp}/model.tf

    yq  --arg url "$url" '.zhao_carr_emulation.model.path |= $url' ../configs/default.yaml > config.yaml
    trap 'rm config.yaml' EXIT

    argo submit ../argo/prog-run-and-eval.yaml \
        --name "$tag" \
        -p image_tag="$image" \
        -p tag=$tag \
        -p config=$(base64 --wrap 0 config.yaml) | grep -v 'config:'
done
