#!/bin/bash
echo ${RANDOM_TAG}
cat << EOF > kustomization/kustomization.yaml
# DO NOT EDIT generated by ../run_integration_with_wait.sh
resources:
- job.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# change this after significant changes to this file
namePrefix: v1-
nameSuffix: "$SUFFIX"
commonLabels:
  waitForMe: "$RANDOM_TAG"
configMapGenerator:
  - name: nudging
    # env: input_data.env
    literals:
    # prognostic_run is changed here
    # this information is not needed to configure the k8s resources
    - PROGNOSTIC_RUN_IMAGE=us.gcr.io/vcm-ml/prognostic_run:$VERSION
    - FV3NET_IMAGE=us.gcr.io/vcm-ml/fv3net:$VERSION
    - JOBNAME=$JOBNAME
    files:
      - train_sklearn_model.yml
      - end_to_end.yaml
images:
- name: us.gcr.io/vcm-ml/fv3net
  newName: us.gcr.io/vcm-ml/fv3net
  newTag: $VERSION
EOF