#!/bin/bash

url=gs://vcm-ml-experiments/microphysics-emulation/2022-01-18/rnn-predict-gscond-3f77ec/checkpoints/epoch.012.tf
tag=rnn-predict-gscond-3f77ec-epoch12
image=373b39524888bb784f488b6af81282de1cd3aed4

argo submit prog-run-and-eval.yaml \
    -p tag=$tag \
    -p image_tag=$image \
    -p config=$(base64 --wrap 0 ../configs/default.yaml) \
    -p tf_model=$url

