#!/bin/bash

url=gs://vcm-ml-experiments/microphysics-emulation/2022-02-22/2ngq1xkl/model.tf
tag=gscond-only-pressure-in-f88c1b-30d-v1
image=latest

yq  --arg url "$url" '.zhao_carr_emulation.gscond.path |= $url' ../configs/default.yaml > config.yaml
trap 'rm config.yaml' EXIT


argo submit prog-run-and-eval.yaml \
    --name "$tag" \
    -p image_tag="$image" \
    -p tag=$tag \
    -p config=$(base64 --wrap 0 config.yaml) | grep -v 'config:' | tee -a submitted-jobs.txt
