#!/bin/bash

# standalone models
# tags=(
#     zcemu-dense-cloudtdep-b0cc65-antarctic-false
#     zcemu-dense-cloudtdep-b0cc65-antarctic-true
#     zcemu-rnn-cloudtdep-b0cc65-antarctic-false
#     zcemu-rnn-cloudtdep-b0cc65-antarctic-true
# )

# blended models
tags=(
    rnn-alltdep-antarctic-blend
    dense-alltdep-antarctic-blend
)



group="$(openssl rand -hex 3)"
image=da1584e7fc1304f72eef69bbef3abec89c414b55

for tag in ${tags[@]}
do

    url=gs://vcm-ml-experiments/microphysics-emulation/2022-02-16/${tag}/model.tf
    run_tag=${tag}-${group}-short

    argo submit ../argo/prog-run-and-eval.yaml \
        -p tag=$run_tag \
        -p image_tag=$image \
        -p config=$(base64 --wrap 0 ../configs/default_short.yaml) \
        -p tf_model=$url

done

