FROM continuumio/miniconda3:latest

RUN apt-get update && apt-get install -y curl gfortran make && \
    apt-get clean && \
    conda update -n base conda && \
    conda clean -i

CMD [ "/bin/bash" ]
