FROM continuumio/miniconda:latest

# https://askubuntu.com/questions/51854/is-it-possible-to-install-a-deb-from-a-url
# linux-libc-dev is a broken uri for the apt-get repository that's checked in miniconda
RUN apt-get install -y curl && \
    curl -L "http://security-cdn.debian.org/debian-security/pool/updates/main/l/linux/linux-libc-dev_4.19.67-2+deb10u2_amd64.deb" > linux-libc-dev.deb && \
    dpkg -i linux-libc-dev.deb && \
    rm -f linux-libc-dev.deb && \
    apt-get install -y gfortran && \
    apt-get install -y make && \
    apt-get clean && \
    conda update -n base conda

CMD [ "/bin/bash" ]
