FROM continuumio/miniconda3:latest

RUN apt-get update && apt-get install -y \
    curl \
    gfortran \
    make \
    uuid \
    gnupg && \
    apt-get clean && \
    conda update -n base conda && \
    conda clean -i

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
    apt-get update && apt-get install -y google-cloud-sdk && \
    gcloud config set project vcm-ml

CMD [ "/bin/bash" ]
