
CONFIG ?= ./fv3config.yaml

create_training:
    ./run_single.sh $(CONFIG) 01
    ./run_single.sh $(CONFIG) 02
    ./run_single.sh $(CONFIG) 03
    ./run_single.sh $(CONFIG) 04
    ./run_single.sh $(CONFIG) 05
    ./run_single.sh $(CONFIG) 06
    ./run_single.sh $(CONFIG) 07
    ./run_single.sh $(CONFIG) 08
    ./run_single.sh $(CONFIG) 09
    ./run_single.sh $(CONFIG) 10
    ./run_single.sh $(CONFIG) 11
    ./run_single.sh $(CONFIG) 12