from .manager import DiagnosticFileConfig, FortranFileConfig

ml_diagnostics = DiagnosticFileConfig(
    name="diags.zarr",
    chunks={"time": 96},
    variables=[
        "net_moistening",
        "net_moistening_diagnostic",
        "net_heating",
        "net_heating_diagnostic",
        "total_precipitation_rate",
        "water_vapor_path",
        "physics_precip",
        "column_integrated_dQu",
        "column_integrated_dQu_diagnostic",
        "column_integrated_dQv",
        "column_integrated_dQv_diagnostic",
    ],
)
nudging_diagnostics_2d = DiagnosticFileConfig(
    name="diags.zarr",
    chunks={"time": 96},
    variables=[
        "net_moistening_due_to_nudging",
        "net_heating_due_to_nudging",
        "net_mass_tendency_due_to_nudging",
        "total_precipitation_rate",
        "water_vapor_path",
        "physics_precip",
    ],
)
nudging_tendencies = DiagnosticFileConfig(
    name="nudging_tendencies.zarr", chunks={"time": 8}, variables=[]
)
physics_tendencies = DiagnosticFileConfig(
    name="physics_tendencies.zarr",
    chunks={"time": 8},
    variables=[
        "tendency_of_air_temperature_due_to_fv3_physics",
        "tendency_of_specific_humidity_due_to_fv3_physics",
        "tendency_of_eastward_wind_due_to_fv3_physics",
        "tendency_of_northward_wind_due_to_fv3_physics",
    ],
)
baseline_diagnostics = DiagnosticFileConfig(
    name="diags.zarr",
    chunks={"time": 96},
    variables=["water_vapor_path", "physics_precip"],
)
state_after_timestep = DiagnosticFileConfig(
    name="state_after_timestep.zarr",
    chunks={"time": 8},
    variables=[
        "x_wind",
        "y_wind",
        "eastward_wind",
        "northward_wind",
        "vertical_wind",
        "air_temperature",
        "specific_humidity",
        "pressure_thickness_of_atmospheric_layer",
        "vertical_thickness_of_atmospheric_layer",
        "land_sea_mask",
        "surface_temperature",
        "surface_geopotential",
        "sensible_heat_flux",
        "latent_heat_flux",
        "total_precipitation",
        "surface_precipitation_rate",
        "total_soil_moisture",
        "total_sky_downward_shortwave_flux_at_surface",
        "total_sky_upward_shortwave_flux_at_surface",
        "total_sky_downward_longwave_flux_at_surface",
        "total_sky_upward_longwave_flux_at_surface",
        "total_sky_downward_shortwave_flux_at_top_of_atmosphere",
        "total_sky_upward_shortwave_flux_at_top_of_atmosphere",
        "total_sky_upward_longwave_flux_at_top_of_atmosphere",
        "clear_sky_downward_shortwave_flux_at_surface",
        "clear_sky_upward_shortwave_flux_at_surface",
        "clear_sky_downward_longwave_flux_at_surface",
        "clear_sky_upward_longwave_flux_at_surface",
        "clear_sky_upward_shortwave_flux_at_top_of_atmosphere",
        "clear_sky_upward_longwave_flux_at_top_of_atmosphere",
        "latitude",
        "longitude",
    ],
)
reference_state = DiagnosticFileConfig(
    name="reference_state.zarr", chunks={"time": 8}, variables=[]
)
sfc_dt_atmos = FortranFileConfig(
    name="sfc_dt_atmos.zarr",
    chunks={"time": 96},
    variables=[
        "lon",
        "lat",
        "lonb",
        "latb",
        "area",
        "uflx",
        "vflx",
        "CPRATsfc",
        "PRATEsfc",
        "ICEsfc",
        "SNOWsfc",
        "GRAUPELsfc",
        "DSWRFsfc",
        "USWRFsfc",
        "DSWRFtoa",
        "USWRFtoa",
        "ULWRFtoa",
        "ULWRFsfc",
        "DLWRFsfc",
        "LHTFLsfc",
        "SHTFLsfc",
        "HPBLsfc",
        "ICECsfc",
        "SLMSKsfc",
        "SPFH2m",
        "TMP2m",
        "TMPsfc",
        "DPT2m",
        "UGRD10m",
        "VGRD10m",
        "TMAX2m",
        "MAXWIND10m",
        "SOILM",
        "SOILT1",
        "SOILT2",
        "SOILT3",
        "SOILT4",
    ],
)
atmos_dt_atmos = FortranFileConfig(
    name="atmos_dt_atmos.zarr",
    chunks={"time": 96},
    variables=[
        "lon",
        "lat",
        "lonb",
        "latb",
        "area",
        "UGRDlowest",
        "UGRD850",
        "UGRD500",
        "UGRD200",
        "UGRD50",
        "VGRDlowest",
        "VGRD850",
        "VGRD500",
        "VGRD200",
        "VGRD50",
        "TMP500_300",
        "TMPlowest",
        "TMP850",
        "TMP500",
        "TMP200",
        "w850",
        "w500",
        "w200",
        "w50",
        "VORT850",
        "VORT500",
        "VORT200",
        "h850",
        "h500",
        "h200",
        "RH1000",
        "RH925",
        "RH850",
        "RH700",
        "RH500",
        "q1000",
        "q925",
        "q850",
        "q700",
        "q500",
        "PRMSL",
        "PRESsfc",
        "PWAT",
        "VIL",
        "iw",
        "kinetic_energy",
        "total_energy",
    ],
)
atmos_8xdaily = FortranFileConfig(
    name="atmos_8xdaily.zarr",
    chunks={"time": 8},
    variables=[
        "lon",
        "lat",
        "lonb",
        "latb",
        "area",
        "ucomp",
        "vcomp",
        "temp",
        "delp",
        "sphum",
        "nhpres",
        "w",
        "delz",
        "ps",
        "reflectivity",
        "liq_wat",
        "ice_wat",
        "rainwat",
        "snowwat",
        "graupel",
    ],
)
nudging_tendencies_fortran = FortranFileConfig(
    name="nudging_tendencies.zarr",
    chunks={"time": 8},
    variables=[
        "lon",
        "lat",
        "lonb",
        "latb",
        "area",
        "u_dt_nudge",
        "v_dt_nudge",
        "delp_dt_nudge",
        "ps_dt_nudge",
        "t_dt_nudge",
        "q_dt_nudge",
    ],
)
