python -m fv3net.pipelines.create_training_data \
--gcs-input-data-path 2019-10-28-X-SHiELD-2019-10-05-multiresolution-extracted/zarr_new_dims/C48 \
--gcs-output-data-dir test-annak/test_dataflow \
--mask-to-surface-type sea \
--gcs-bucket gs://vcm-ml-data \
--job_name test-job-create-training-data \
--project vcm-ml \
--region us-central1 \
--runner DataflowRunner \
--temp_location gs://vcm-ml-data/tmp_dataflow \
--num_workers 4 \
--max_num_workers 20 \
--disk_size_gb 30 \
--worker_machine_type n1-standard-1 \
--setup_file ./setup.py \
--extra_package external/vcm/dist/vcm-0.1.0.tar.gz
