apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin
  namespace: default
rules:
- apiGroups:
  - ""
  - batch
  resources:
  - pods
  - services
  - persistentvolumes
  - persistentvolumeclaims
  - jobs
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
