#!/bin/bash

exps=(
    "limit-tests-all-loss-dense-7ef273"
    "limit-tests-base-dense-7ef273"
    "limit-tests-limiter-all-loss-dense-7ef273"
    "limit-tests-limiter-dense-7ef273"
)


image=latest

for exp in ${exps[@]}
do
    # tag=$(echo $exp | sed --expression='s/^.\{11\}//')-30d-v1
    tag=$exp-30d-v1
    url=gs://vcm-ml-experiments/microphysics-emulation/2022-03-02/$exp/model.tf

    yq  --arg url "$url" '.zhao_carr_emulation.model.path |= $url' ../configs/default.yaml > config.yaml
    trap 'rm config.yaml' EXIT

    argo submit ../argo/prog-run-and-eval.yaml \
        --name "$tag" \
        -p image_tag="$image" \
        -p tag=$tag \
        -p config=$(base64 --wrap 0 config.yaml) | grep -v 'config:'
done

